### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by sec13b** [wh0amitz/SharpADWS#1]
can you add SharpADWS.exe in Packages?

C:\Users\work\Desktop\SharpADWS\SharpADWS\bin\Debug>SharpADWS.exe Cache

Unhandled Exception: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.ServiceModel.EndpointAddress..ctor(String uri)
   at SharpADWS.ADWS.Enumeration.EnumerateRequest.Enumerate(String filter, String searchBase, String searchScope, IList`1 attributeList) in C:\Users\work\Desktop\SharpADWS\SharpADWS\ADWS\Enumeration\EnumerateRequest.cs:line 39
   at SharpADWS.Program.Run(Options options) in C:\Users\work\Desktop\SharpADWS\SharpADWS\Program.cs:line 156
   at SharpADWS.Program.Main(String[] args) in C:\Users\work\Desktop\SharpADWS\SharpADWS\Program.cs:line 36

C:\Users\work\Desktop\SharpADWS\SharpADWS\bin\Debug>

**Comment by wh0amitz** [comment]
Please ensure that Active Directory Domain Service exists in your current running environment

**Comment by wh0amitz** [comment]
Please make sure that Active Directory domain service exists in your current operating environment, or use -d to specify the current domain name.
